services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URI: "http://localhost:8081"
      USER_SERVICE_URI: "http://localhost:8082"
      MOVIE_SERVICE_URI: "http://localhost:8083"
      ARTIST_SERVICE_URI: "http://localhost:8084"
      RESERVATION_SERVICE_URI: "http://localhost:8085"
      REVIEW_SERVICE_URI: "http://localhost:8086"
      PAYMENT_SERVICE_URI: "http://localhost:8087"
      POSTER_SERVICE_URI: "http://localhost:8088"
      SCRAPPING_SERVICE_URI: "http://localhost:8089"
      KEYCLOAK_ISSUER_URI: "http://localhost:8081/realms/media-app"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
