server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
        # API Authentification
          - id: authentification-api
            uri: http://localhost:8081
            predicates:
              - Path=/api/auth/**
            filters:
              - StripPrefix=1

        # API Utilisateur
          - id: user-api
            uri: http://localhost:8082
            predicates:
              - Path=/api/user/**
            filters:
              - StripPrefix=1

          # API Films
          - id: movie-api
            uri: http://localhost:8083
            predicates:
              - Path=/api/movies/**
            filters:
              - StripPrefix=1

          # API Artistes
          - id: artist-api
            uri: http://localhost:8084
            predicates:
              - Path=/api/artists/**
            filters:
              - StripPrefix=1

          # API RÃ©servations
          - id: reservation-api
            uri: http://localhost:8085
            predicates:
              - Path=/api/reservation/**
            filters:
              - StripPrefix=1

          # API Reviews
          - id: review-api
            uri: http://localhost:8086
            predicates:
              - Path=/api/review/**
            filters:
              - StripPrefix=1

          # API Payment
          - id: payment-api
            uri: http://localhost:8087
            predicates:
              - Path=/api/payment/**
            filters:
              - StripPrefix=1

          # API Affiches
          - id: poster-api
            uri: http://localhost:8088
            predicates:
              - Path=/api/poster/**
            filters:
              - StripPrefix=1

          # API Scrapping
          - id: scrapping-api
            uri: http://localhost:8089
            predicates:
              - Path=/api/scrapping/**
            filters:
              - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/media-app
