server:
  port: 8080

services:
  auth-uri: ${AUTH_SERVICE_URI}
  user-uri: ${USER_SERVICE_URI}
  movie-uri: ${MOVIE_SERVICE_URI}
  artist-uri: ${ARTIST_SERVICE_URI}
  reservation-uri: ${RESERVATION_SERVICE_URI}
  review-uri: ${REVIEW_SERVICE_URI}
  payment-uri: ${PAYMENT_SERVICE_URI}
  poster-uri: ${POSTER_SERVICE_URI}
  scrapping-uri: ${SCRAPPING_SERVICE_URI}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
        # API Authentification
          - id: authentification-api
            uri: ${services.auth-uri}
            predicates:
              - Path=/api/auth/**
            filters:
              - StripPrefix=1

        # API Utilisateur
          - id: user-api
            uri: ${services.user-uri}
            predicates:
              - Path=/api/user/**
            filters:
              - StripPrefix=1

          # API Films
          - id: movie-api
            uri: ${services.movie-uri}
            predicates:
              - Path=/api/movies/**
            filters:
              - StripPrefix=1

          # API Artistes
          - id: artist-api
            uri: ${services.artist-uri}
            predicates:
              - Path=/api/artists/**
            filters:
              - StripPrefix=1

          # API RÃ©servations
          - id: reservation-api
            uri: ${services.reservation-uri}
            predicates:
              - Path=/api/reservation/**
            filters:
              - StripPrefix=1

          # API Reviews
          - id: review-api
            uri: ${services.review-uri}
            predicates:
              - Path=/api/review/**
            filters:
              - StripPrefix=1

          # API Payment
          - id: payment-api
            uri: ${services.payment-uri}
            predicates:
              - Path=/api/payment/**
            filters:
              - StripPrefix=1

          # API Affiches
          - id: poster-api
            uri: ${services.poster-uri}
            predicates:
              - Path=/api/poster/**
            filters:
              - StripPrefix=1

          # API Scrapping
          - id: scrapping-api
            uri: ${services.scrapping-uri}
            predicates:
              - Path=/api/scrapping/**
            filters:
              - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
